apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapzzi-backend
  namespace: superminds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tapzzi-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tapzzi-backend
    spec:
      containers:
        - name: tapzzi-backend
          image: registry.digitalocean.com/fabs/tapzzi-backend:${{ env.IMAGE_TAG }}
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
        - name: fabs